# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "hazelcast-jars"
  s.version = "3.0.SNAPSHOT"
  s.platform = "jruby"

  s.required_rubygems_version = Gem::Requirement.new("> 1.3.1") if s.respond_to? :required_rubygems_version=
  s.authors = ["Adrian Madrid"]
  s.date = "2013-07-11"
  s.description = "Something to make my life easier."
  s.email = "aemadrid@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "VERSION_EXT",
    "hazelcast-jars.gemspec",
    "lib/hazelcast-3.0-SNAPSHOT.jar",
    "lib/hazelcast-all-3.0-SNAPSHOT.jar",
    "lib/hazelcast-client-3.0-SNAPSHOT.jar",
    "lib/hazelcast-jars.rb",
    "lib/hazelcast-jars/hazelcast-jars.rb",
    "lib/hazelcast-jars/version.rb"
  ]
  s.homepage = "http://github.com/aemadrid/hazelcast-jars"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubyforge_project = "hazelcast-jars"
  s.rubygems_version = "1.8.23"
  s.summary = "Utility gem to carry the latest Hazelcast jars."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

